import { CameraPromptData } from "../../../codes";

export const UNKNOWN: CameraPromptData<"0300"> = {
		code: "0300",
		type: "destructive",
		title: "Erro desconhecido",
		illustration: "paymentError",
		userDescription: "Ocorreu um erro que impossibilitou a abertura da câmera.",
		userResolution: "Por favor tente novamente.",
		internalDescription: "Ocorreu um erro desconhecido ao abrir a câmera",
		additionalData: undefined,
	},
	NOT_ALLOWED: CameraPromptData<"0301"> = {
		code: "0301",
		type: "destructive",
		title: "Permissão negada",
		illustration: "paymentError",
		userDescription: "",
		userResolution: "Por favor conceda acesso a câmera através das configurações do seu navegador.",
		internalDescription: "O app não tem permissão para utilizar a camera do usuario",
		additionalData: undefined,
	},
	NOT_FOUND: CameraPromptData<"0302"> = {
		code: "0302",
		type: "destructive",
		title: "Nenhuma câmera encontrada",
		illustration: "paymentError",
		userDescription: "Nenhum dispositivo para captura de imagens foi encontrado.",
		userResolution: "Por favor efetue essa operação em um dispositivo com câmera.",
		internalDescription: "Nenhum dispositivo para captura de imagens foi encontrado.",
		additionalData: undefined,
	},
	NOT_READABLE: CameraPromptData<"0303"> = {
		code: "0303",
		type: "destructive",
		title: "Câmera com problemas",
		illustration: "paymentError",
		userDescription: "Devido a um problema na câmera, ela não pode ser aberta.",
		userResolution: "Por favor tente em outro dispositivo.",
		internalDescription: "Houve um problema ao tentar abrir a câmera",
		additionalData: undefined,
	},
	BROWSER_EXCEPTION: CameraPromptData<"0304"> = {
		code: "0304",
		type: "destructive",
		title: "Browser não suportado",
		illustration: "paymentError",
		userDescription: "A apple atualmente impede que browsers diferentes do safari acessem sua câmera.",
		userResolution: "Por favor utilize o safari para completar essa operação.",
		internalDescription: "Browser não suporta câmera",
		additionalData: undefined,
	};
