import { RegisterCardPromptData } from "../../../../codes";

export const WRONG_TRANSACTION_VALUE: RegisterCardPromptData<"0001"> = {
		code: "0001",
		type: "destructive",
		title: "Valor incorreto",
		illustration: "paymentError",
		userDescription: "O valor digitado não corresponde ao valor na fatura.",
		userResolution: "Verifique a fatura e digite novamente.",
		internalDescription: "O usuário colocou o valor errado.",
		additionalData: undefined,
	},
	CONFIRM_TRANSACTION: RegisterCardPromptData<"0002"> = {
		code: "0002",
		type: "destructive",
		title: "Seu cartão irá expirar",
		illustration: "paymentError",
		userDescription:
			"Ao cadastrar o cartão, você marcou que ele expira após uma compra. Iremos enviar uma transação de baixo valor na sua fatura, o que fará seu cartão expirar.",
		userResolution: "Deseja continuar?",
		internalDescription: "O usuário está requisitando uma nova transação com um cartão que expira após uma compra",
		additionalData: undefined,
	},
	INITIAL_TRANSACTION: RegisterCardPromptData<"0003"> = {
		code: "0003",
		type: "neutral",
		title: "Verifique sua fatura do cartão",
		illustration: "noteList",
		userDescription: "Para sua segurança, o vendedor solicitou a validação do titular.",
		userResolution: "Verifique a fatura do seu cartão e digite o valor recebido.",
		internalDescription: "O usuário iniciou a verificação através de uma transação",
		additionalData: undefined,
	},
	TRANSACTION_SEND: RegisterCardPromptData<"0004"> = {
		code: "0004",
		type: "success",
		title: "Transação enviada com sucesso",
		illustration: "noteList",
		userDescription: "Uma nova transação foi enviada.",
		userResolution: "Verifique na fatura e digite o novo valor no app.",
		internalDescription: "Transação enviada com sucesso para o usuário",
		additionalData: undefined,
	},
	WRONG_SEND_TRANSACTION: RegisterCardPromptData<"0005"> = {
		code: "0005",
		type: "destructive",
		title: "Falha ao enviar transação",
		illustration: "paymentError",
		userDescription: "Ocorreu um erro ao enviarmos uma nova transação.",
		userResolution: "Tente novamente mais tarde.",
		internalDescription: "Falha ao enviar nova transação para o usuário",
		additionalData: undefined,
	};
