import { RedePromptData } from "../../codes";

export const PROBLEMS_ON_THE_CARD: RedePromptData<"2100", "101"> = {
		code: "2100",
		type: "destructive",
		title: "Contate seu banco",
		illustration: "profileData",
		userDescription: "O emissor do cartão (seu banco) recusou a transação.",
		userResolution: "Fale com seu banco para liberar o cartão e tente novamente.",
		internalDescription: "Adquirente retornou: '101 - Unauthorized. Problems on the card, contact the issuer.'",
		additionalData: { response_code: "101" },
	},
	PROBLEMS_WITH_STORE: RedePromptData<"2101", "102"> = {
		code: "2101",
		type: "destructive",
		title: "Contate seu banco",
		illustration: "profileData",
		userDescription: "O emissor do cartão (seu banco) recusou a transação.",
		userResolution: "Fale com seu banco para liberar o cartão e tente novamente.",
		internalDescription: "Adquirente retornou: '102 - Unauthorized. Check the situation of the store with the issuer.'",
		additionalData: { response_code: "102" },
	},
	UNAUTHORIZED1: RedePromptData<"2102", "103"> = {
		code: "2102",
		type: "destructive",
		title: "Contate seu banco",
		illustration: "profileData",
		userDescription: "O emissor do cartão (seu banco) recusou a transação.",
		userResolution: "Fale com seu banco para liberar o cartão e tente novamente.",
		internalDescription: "Adquirente retornou: '103 - Unauthorized. Please try again.'",
		additionalData: { response_code: "103" },
	},
	UNAUTHORIZED2: RedePromptData<"2103", "104"> = {
		code: "2103",
		type: "destructive",
		title: "Contate seu banco",
		illustration: "profileData",
		userDescription: "O emissor do cartão (seu banco) recusou a transação.",
		userResolution: "Fale com seu banco para liberar o cartão e tente novamente.",
		internalDescription: "Adquirente retornou: '104 - Unauthorized. Please try again.'",
		additionalData: { response_code: "104" },
	},
	RESTRICTED_CARD: RedePromptData<"2104", "105"> = {
		code: "2104",
		type: "destructive",
		title: "Contate seu banco",
		illustration: "profileData",
		userDescription: "O emissor do cartão (seu banco) recusou a transação.",
		userResolution: "Fale com seu banco para liberar o cartão e tente novamente.",
		internalDescription: "Adquirente retornou: '105 - Unauthorized. Restricted card.'",
		additionalData: { response_code: "105" },
	},
	ERROR_IN_ISSUER_PROCESSING: RedePromptData<"2105", "106"> = {
		code: "2105",
		type: "destructive",
		title: "Contate seu banco",
		illustration: "profileData",
		userDescription: "O emissor do cartão (seu banco) recusou a transação.",
		userResolution: "Fale com seu banco para liberar o cartão e tente novamente.",
		internalDescription: "Adquirente retornou: '106 - Error in issuer processing. Please try again.'",
		additionalData: { response_code: "106" },
	},
	UNAUTHORIZED3: RedePromptData<"2106", "107"> = {
		code: "2106",
		type: "destructive",
		title: "Contate seu banco",
		illustration: "profileData",
		userDescription: "O emissor do cartão (seu banco) recusou a transação.",
		userResolution: "Fale com seu banco para liberar o cartão e tente novamente.",
		internalDescription: "Adquirente retornou: '107 - Unauthorized. Please try again.'",
		additionalData: { response_code: "107" },
	},
	VALUE_NOT_ALLOWED_FOR_THIS_TYPE_OF_CARD: RedePromptData<"2107", "108"> = {
		code: "2107",
		type: "destructive",
		title: "Contate seu banco",
		illustration: "profileData",
		userDescription: "O emissor do cartão (seu banco) recusou a transação.",
		userResolution: "Fale com seu banco para liberar o cartão e tente novamente.",
		internalDescription: "Adquirente retornou: '108 - Unauthorized. Value not allowed for this type of card.'",
		additionalData: { response_code: "108" },
	},
	NONEXISTENT_CARD: RedePromptData<"2108", "109"> = {
		code: "2108",
		type: "destructive",
		title: "Contate seu banco",
		illustration: "profileData",
		userDescription: "O emissor do cartão (seu banco) informou que o cartão não existe.",
		userResolution: "Fale com seu banco para corrigir o problema e tente novamente.",
		internalDescription: "Adquirente retornou: '109 - Unauthorized. Nonexistent card.'",
		additionalData: { response_code: "109" },
	},
	TRANSACTION_TYPE_NOT_ALLOWED_FOR_THIS_CARD: RedePromptData<"2109", "110"> = {
		code: "2109",
		type: "destructive",
		title: "Contate seu banco",
		illustration: "profileData",
		userDescription: "O emissor do cartão (seu banco) recusou a transação.",
		userResolution: "Fale com seu banco para liberar o cartão e tente novamente.",
		internalDescription: "Adquirente retornou: '110 - Unauthorized. Transaction type not allowed for this card.'",
		additionalData: { response_code: "110" },
	},
	INSUFFICIENT_FUNDS: RedePromptData<"2110", "111"> = {
		code: "2110",
		type: "destructive",
		title: "Cartão sem saldo",
		illustration: "profileData",
		userDescription: "O emissor do cartão (seu banco) recusou a transação por falta de saldo.",
		userResolution: "Fale com seu banco para liberar o cartão e tente novamente.",
		internalDescription: "Adquirente retornou: '111 - Unauthorized. Insufficient funds.'",
		additionalData: { response_code: "111" },
	},
	EXPIRY_DATE_EXPIRED: RedePromptData<"2111", "112"> = {
		code: "2111",
		type: "destructive",
		title: "Cartão vencido",
		illustration: "profileData",
		userDescription: "O emissor do cartão (seu banco) recusou a transação por que este cartão está expirado.",
		userResolution: "Fale com seu banco para liberar o cartão ou cadastre outro cartão.",
		internalDescription: "Adquirente retornou: '112 - Unauthorized. Expiry date expired.'",
		additionalData: { response_code: "112" },
	},
	IDENTIFIED_MODERATE_RISK_BY_THE_ISSUER: RedePromptData<"2112", "113"> = {
		code: "2112",
		type: "destructive",
		title: "Contate seu banco",
		illustration: "profileData",
		userDescription: "O emissor do cartão (seu banco) recusou a transação.",
		userResolution: "Fale com seu banco para liberar o cartão e tente novamente.",
		internalDescription: "Adquirente retornou: '113 - Unauthorized. Identified moderate risk by the issuer.'",
		additionalData: { response_code: "113" },
	},
	THE_CARD_DOES_NOT_BELONG_TO_THE_PAYMENT_NETWORK: RedePromptData<"2113", "114"> = {
		code: "2113",
		type: "destructive",
		title: "Contate seu banco",
		illustration: "profileData",
		userDescription: "O emissor do cartão (seu banco) recusou a transação.",
		userResolution: "Fale com seu banco para liberar o cartão e tente novamente.",
		internalDescription: "Adquirente retornou: '114 - Unauthorized. The card does not belong to the payment network.'",
		additionalData: { response_code: "114" },
	},
	EXCEEDED_THE_LIMIT_OF_TRANSACTIONS_ALLOWED_IN_THE_PERIOD: RedePromptData<"2114", "115"> = {
		code: "2114",
		type: "destructive",
		title: "Quantidade de uso acima da permitida",
		illustration: "profileData",
		userDescription: "O emissor do cartão (seu banco) recusou a transação por exceder a quantidade de usos permitida no período.",
		userResolution: "Fale com seu banco para liberar o cartão e tente novamente.",
		internalDescription: "Adquirente retornou: '115 - Unauthorized. Exceeded the limit of transactions allowed in the period.'",
		additionalData: { response_code: "115" },
	},
	CONTACT_THE_CARD_ISSUER: RedePromptData<"2115", "116"> = {
		code: "2115",
		type: "destructive",
		title: "Contate seu banco",
		illustration: "profileData",
		userDescription: "O emissor do cartão (seu banco) recusou a transação.",
		userResolution: "Fale com seu banco para liberar o cartão e tente novamente.",
		internalDescription: "Adquirente retornou: '116 - Unauthorized. Please contact the Card Issuer.'",
		additionalData: { response_code: "116" },
	},
	TRANSACTION_NOT_FOUND: RedePromptData<"2116", "117"> = {
		code: "2116",
		type: "destructive",
		title: "Contate seu banco",
		illustration: "profileData",
		userDescription: "O emissor do cartão (seu banco) recusou a transação.",
		userResolution: "Fale com seu banco para liberar o cartão e tente novamente.",
		internalDescription: "Adquirente retornou: '117 - Transaction not found.'",
		additionalData: { response_code: "117" },
	},
	CARD_LOCKED: RedePromptData<"2117", "118"> = {
		code: "2117",
		type: "destructive",
		title: "Cartão bloqueado",
		illustration: "profileData",
		userDescription: "O emissor do cartão (seu banco) recusou a transação por este estar bloqueado.",
		userResolution: "Fale com seu banco para liberar o cartão e tente novamente.",
		internalDescription: "Adquirente retornou: '118 - Unauthorized. Card locked.'",
		additionalData: { response_code: "118" },
	},
	INVALID_SECURITY_CODE: RedePromptData<"2118", "119"> = {
		code: "2118",
		type: "destructive",
		title: "Código de segurança incorreto",
		illustration: "profileData",
		userDescription: "O emissor do cartão (seu banco) recusou a transação devido ao código de segurança estar incorreto.",
		userResolution: "Refaça o cadastro do cartão e tente novamente.",
		internalDescription: "Adquirente retornou: '119 - Unauthorized. Invalid security code'",
		additionalData: { response_code: "119" },
	},
	ERROR_PROCESSING: RedePromptData<"2119", "121"> = {
		code: "2119",
		type: "destructive",
		title: "Contate seu banco",
		illustration: "profileData",
		userDescription: "O emissor do cartão (seu banco) recusou a transação.",
		userResolution: "Fale com seu banco para liberar o cartão e tente novamente.",
		internalDescription: "Adquirente retornou: '121 - Error processing. Please try again'",
		additionalData: { response_code: "121" },
	},
	TRANSACTION_PREVIOUSLY_SENT: RedePromptData<"2120", "122"> = {
		code: "2120",
		type: "destructive",
		title: "Contate seu banco",
		illustration: "profileData",
		userDescription: "O emissor do cartão (seu banco) recusou a transação.",
		userResolution: "Fale com seu banco para liberar o cartão e tente novamente.",
		internalDescription: "Adquirente retornou: '122 - Transaction previously sent'",
		additionalData: { response_code: "122" },
	},
	BEARER_REQUESTED_THE_END_OF_THE_RECURRENCES_IN_THE_ISSUER: RedePromptData<"2121", "123"> = {
		code: "2121",
		type: "destructive",
		title: "Contate seu banco",
		illustration: "profileData",
		userDescription: "O emissor do cartão (seu banco) recusou a transação.",
		userResolution: "Fale com seu banco para liberar o cartão e tente novamente.",
		internalDescription: "Adquirente retornou: '123 - Unauthorized. Bearer requested the end of the recurrences in the issuer.'",
		additionalData: { response_code: "123" },
	},
	CONTACT_REDE: RedePromptData<"2122", "124"> = {
		code: "2122",
		type: "destructive",
		title: "Contate seu banco",
		illustration: "profileData",
		userDescription: "O emissor do cartão (seu banco) recusou a transação.",
		userResolution: "Fale com seu banco para liberar o cartão e tente novamente.",
		internalDescription: "Adquirente retornou: '124 - Unauthorized. Contact Rede'",
		additionalData: { response_code: "124" },
	},
	ZERO_DOLLAR_TRANSACTION_NOT_ALLOWED_FOR_THIS_CARD: RedePromptData<"2123", "170"> = {
		code: "2123",
		type: "destructive",
		title: "Contate seu banco",
		illustration: "profileData",
		userDescription: "O emissor do cartão (seu banco) recusou a transação.",
		userResolution: "Fale com seu banco para liberar o cartão e tente novamente.",
		internalDescription: "Adquirente retornou: '170 - Zero dollar transaction not allowed for this card.'",
		additionalData: { response_code: "170" },
	},
	TRANSACTION_ALREADY_CAPTURED: RedePromptData<"2124", "172"> = {
		code: "2124",
		type: "destructive",
		title: "Contate seu banco",
		illustration: "profileData",
		userDescription: "O emissor do cartão (seu banco) recusou a transação.",
		userResolution: "Fale com seu banco para liberar o cartão e tente novamente.",
		internalDescription: "Adquirente retornou: '172 - transaction already captured.'",
		additionalData: { response_code: "172" },
	},
	ZERO_DOLLAR_TRANSACTION_DENIED: RedePromptData<"2125", "175"> = {
		code: "2125",
		type: "destructive",
		title: "Contate seu banco",
		illustration: "profileData",
		userDescription: "O emissor do cartão (seu banco) recusou a transação.",
		userResolution: "Fale com seu banco para liberar o cartão e tente novamente.",
		internalDescription: "Adquirente retornou: '175 - Zero dollar transaction denied. '",
		additionalData: { response_code: "175" },
	};
